export { default as MainScreen } from './Main'
export { default as AssistantScreen } from './Assistant'
export { default as AssistantChatScreen } from './AssistantChat'
export { default as AppointmentScreen } from './Appointment'
export { default as AddAppointmentScreen } from './AddAppointment'
export { default as RegisterScreen } from './Register'
export { default as LoginScreen } from './Login'
